### ISSUE TITLE
Low pull-ups

### ISSUE THREAD

**Issue by kakl** [UniversalScientificTechnologies/AIRDOS04#16]
Vsude jsou pouzity prilis male hodnoty pull-ups a pull-downs. Ted jsou osazeny odpory 1 k a temi tece zbytecne velky proud. Lepe treba 68 k. Take na I2C jsou odpory 1k. Podle specifikace by melo byt tusim 4 j nebo 10 k podle vzdalenosti a rychlosti.

**Comment by kaklik** [comment]
Vyřešeno v revizi B.
