### ISSUE TITLE
Too transparent PCB

### ISSUE THREAD

**Issue by kakl** [UniversalScientificTechnologies/AIRDOS04#18]
PCB s diodou je prilis prusvitne. Pod diodu je treba dat neprusvitnou podlozku. Treba cernou elektrikarskou pasku.

**Comment by kaklik** [comment]
To řešení s černou izolační páskou jsi testoval, že funguje? 
Jinak je to redundatní k tomuhle: https://github.com/kaklik/USTSIPIN03/issues/2
