### ISSUE TITLE
PCB remove detection

### ISSUE THREAD

**Issue by kakl** [UniversalScientificTechnologies/AIRDOS04#19]
V souvislosti s dobijenim akumulatoru a prenosem dat je treba vyresit logiku detekce vysunuti PCB s procesorem z Molex konektoru.

**Comment by kaklik** [comment]
a to HW řešení, které tam je teď nefunguje, nebo v čem je problém?

**Comment by kaklik** [comment]
DoD: Zařízení pípne když se vloží do krabičky AIRDOSu a pípne, když se vyndá.

**Comment by evakott** [comment]
Co se má stát při vysouvání/zasouvání?
Když se to vysune, tak to bude 10s čekat, 10s si stěžovat a pak se to vypne a udělá se zápis do registru. Zavře se soubor na SD kartě pokud by byl otevřený.
Když se to zasune, tak se to hned zapne pomocí nabíječky (přijde reset). Po resetu se to samo zapne.

**Comment by kaklik** [comment]
Aktuální řešení funguje, ale existuje riziko že za zvýšené teploty se AIRDOS po složení nezapne.  Myslím že nyní je správný postup to napsat do manuálu. Ve formě informace že za zvýšené teploty se zařízení samo nezapne, ale že pokud to uživatel chce přesto zapnout, tak lze udělat override pomocí tlačítka.

**Comment by evakott** [comment]
Co je to zvýšená teplota? Od kolika stupňů Celsia?

**Comment by evakott** [comment]
Napsáno do manuálu obecně do kapitoly Troubleshooting

**Comment by kaklik** [comment]
> Co je to zvýšená teplota? Od kolika stupňů Celsia?

Nevíme.
