### ISSUE TITLE
Programing through Molex

### ISSUE THREAD

**Issue by kakl** [UniversalScientificTechnologies/AIRDOS04#20]
Aby slo programovat procesor pres Molex konektor, je treba na nej vyvest RESAT pres kondenzator. Asi druhy kondenzator pripojeny do stejneho bodu jako kondenzator od DTR FTDI.

**Comment by kaklik** [comment]
Vyřešeno ve verzi B bez dalšího kondenzátoru.

**Comment by kaklik** [comment]
Tohle vyžaduje změnu bootloaderu, takže to není produkčně aplikovatelné.

**Comment by roman-dvorak** [comment]
Já vím, že to vyžaduje změnu bootloaderu, předpokládám, že bude bootloader nastavený na UART1. Alternativně by bylo možné, vyvést i UART0 do molexu pro účely programování. To by pak nevyžadovalo úpravy bootloaderu.

**Comment by kakl** [comment]
Jak by se ale potom prepinaly signaly TX a RX mezi Molexem a FTDI?
nejak pres odpory?

**Comment by kaklik** [comment]
Tohle tohle nechejme jako alternativní backup řešení pro případ, že by vážně nešlo vyřešit programování přes HID.
