### ISSUE TITLE
Molex geometry

### ISSUE THREAD

**Issue by kakl** [UniversalScientificTechnologies/AIRDOS04#21]
Je treba upravit PCB s procesorem, aby do nej sel zastrcit Molex konektor. Musi se preroutovat cesty 5V a 3V3, aby na PCB mohl byt vyrez na konektor.

**Comment by kaklik** [comment]
Tohle je už opravené v revizi B: https://github.com/mlab-modules/BATDATUNIT01/tree/BATDATUNIT01B
