### ISSUE TITLE
UART over HID

### ISSUE THREAD

**Issue by kakl** [UniversalScientificTechnologies/AIRDOS04#22]
Nedari se cist data z UARTu pres HID. Z nejakeho duvodu zalezi na tom, kdy se zacne s HID zarizenim komunikovat.

**Comment by kaklik** [comment]
- Uzpůsobit datovou zprávu, tak aby se vešla do 60 bytes (na test i méně) 
- Změnit strukturu zprávy tak, aby identifikace zprávy byla bajt místo $HIST. Například první bajt 0xD0a kanály v podobě Word 0-29, 0xD1 a kanály 30-59, ... 
- zkusit menší baudrate
- možná zkusit jinou konfiguraci UARTU

**Comment by evakott** [comment]
Detekce připojení USB má být na PC5
![393849147_722027939803547_529175124286148079_n](https://github.com/roman-dvorak/AIRDOS04/assets/137726417/8eda6b41-0023-49f9-a246-e47418a7407e)

**Comment by kaklik** [comment]
Už je to implementované a zatím to zřejmě funguje. Další testování bude probíhat na následujícím prototypu.
