### ISSUE TITLE
SD card reader oscillator selection

### ISSUE THREAD

**Issue by kakl** [UniversalScientificTechnologies/AIRDOS04#23]
SD card reader nefunguje bez krystalu.

**Comment by kaklik** [comment]
Oscilátor je na nové revizi už přidaný. Spíš je nutné vybrat vhodný typ, který má nízkou spotřebu ve vypnutém stavu. Výběr oscilátorů pro frekvenci 19,2MHz ale [není moc velký](https://cz.mouser.com/c/passive-components/frequency-control-timing-devices/oscillators/?frequency=19.2%20MHz~~19.2%20MHz%2C%2026%20MHz&supply%20voltage%20-%20min=1.8%20V~~3.3%20V&termination%20style=SMD%2FSMT&instock=y&rp=passive-components%2Ffrequency-control-timing-devices%2Foscillators%7C~Frequency%7C~Supply%20Voltage%20-%20Min&sort=pricing).. 

- ~~https://www.tme.eu/cz/details/19.20m-iqxo-542/krystalove-generatory-smd/iqd-frequency-products/lfspxo056188cutt/~~ velmi malé pouzdro a nemůže být napájen z 3.3V. 
- https://cz.mouser.com/ProductDetail/SiTime/SiT1602BI-13-XXS-19.200000D?qs=sGAEpiMZZMtldj7qu1ydrULysZ4WjdCNGoDRX3i%2F5U6W73MkZ6WdMw%3D%3D

**Comment by kaklik** [comment]
Zkusit objednat i jiné frekvence oscilátoru.

**Comment by kaklik** [comment]
> Zkusit objednat i jiné frekvence oscilátoru.

Tak z jiných frekvencí oscilátorů bude zítra k dispozici akorát 12MHz.
