### ISSUE TITLE
Create a new file for every power-up 

### ISSUE THREAD

**Issue by kaklik** [UniversalScientificTechnologies/AIRDOS04#29]
Pro parserování měření by se hodilo, kdyby nové měření bylo vždy v novém souboru. Aktuální implementace zapisuje doposledního souboru, dokud velikost souboru nepřekročí MAXFILESIZE.  Následně vznikne další soubor až do MAXFILES (200) souborů. Do posledního souboru se zapisuje neustále. 

Důvodem této implementace je, aby mrtvá doba detektoru způsobená zápisem na SDkartu byla udržena v únosných mezích.

**Comment by kakl** [comment]
Je to tak udelano proto, aby pripadna chyba nezpusobila vytvoreni velkeho poctu souboru. Dalsi moznost je, ze se pri vybiti baterii bude opakovat resetart FW. To by take vedlo k vytvoreni novych souboru.

**Comment by kaklik** [comment]
Zatím to vypadá, že současná implementace je dostatečná.
