### ISSUE TITLE
Výroba MLAB modulů pro prototyp AIRDOS04

### ISSUE THREAD

**Issue by evakott** [UniversalScientificTechnologies/AIRDOS04#3]
Výroba prototypu AIRDOS04 z MLAB modulů dle zadání v dokumentu Detektory ionizujícího záření jako produkty UST.

**Comment by evakott** [comment]
Včetně finální kontroly modulů před zadáním plošných spojů do výroby.

**Comment by kaklik** [comment]
Vyřešeno.
